concurrent: 16

replicas: 2

nodeSelector:
  physical: 'yes'

rbac:
  create: true
serviceAccount:
  create: true
  name: gitlab-runner

gitlabUrl: "https://gitlab.example.com"
runnerRegistrationToken: "glrt-xxxxxxxx"

runners:
  config: |
    [[runners]]
      name = "example.com"
      request_concurrency = 2
      [runners.kubernetes]
        image = "golang:1.26-bookworm"
        image_pull_secrets = ["docker-infra-secret"]
